config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboards", to: "dashboards#show"
  resources :events do
    resources :invitations, only: [:create, :update, :destroy ]
    resources :messages, only: [:create]
  end

  patch '/events/:event_id/messages', to: "messages#update"

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :photo
  belongs_to :user

  has_many :invitations, dependent: :destroy
  has_many :users, through: :invitations
  has_many :messages, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :events
  has_many :invitations
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def logged_in?
    !current_user.nil?
  end

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :role, :rider, :details, :address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname, :role, :rider, :details, :address, :photo])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @invitations = Invitation.where(user: current_user)
    @events = Event.where(user: current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to dashboards_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :role)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(user_id: current_user.id)
    start_date = params.fetch(:date, Date.today).to_date
    @events_month = Event.where(date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).where(user_id: current_user.id)


    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @events = Event.where(sql_query, query: "%#{params[:query]}%")
    else
      @events = Event.where(user: current_user) + Event.joins(:invitations).where(invitations: { user: current_user }, invitations: { status: true } )
      @events.uniq!
    end
# find all events where user_id is current_user.id OR event.invitations.user_id = current_user.id
  end

  def show
    @event = Event.find(params[:id])
    @invitation = Invitation.new
    @message = Message.new
    @markers = [{ lat: @event.latitude, lng: @event.longitude }]
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  private



  def event_params
    params.require(:event).permit(:travel, :date, :accomodation, :food, :category, :technician, :rider, :driver, :name, :address, :photo, :performers, :guestlist)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.where(user: current_user)
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.event_id = params[:event_id]
    if @invitation.user = User.where("email ILIKE ?", "%#{params[:invitation][:user_id]}%").first
      @invitation.save!
      flash[:alert] = "Invitation requested!"
    else
      flash[:alert] = "invitation failed"
    end
    redirect_to event_path(params[:event_id])
  end

  def update
    @invitation = Invitation.find(params[:id])
    if params[:status] == "true"
      @invitation.update(status: true)
      flash[:alert] = "Invitation approved!"
      redirect_to event_path(params[:event_id])
    else
      @invitation.update(status: false)
      flash[:alert] = "Invitation declined!"
      redirect_to  dashboards_path
    end

  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to dashboards_path
  end

  private

  def invitation_params
    params.require(:invitation).permit(:user_id, :content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :update

  def create
    @event = Event.find(params[:event_id])
    @message = Message.new(message_params)
    @message.event = @event
    @message.user = current_user
    if @message.save!
      EventChannel.broadcast_to(
        @event,
        render_to_string(partial: "message", locals: {message: @message})
      )
      #  redirect_to event_path(@event, anchor: "message-#{@message.id}")
    else
      render "events/show"
    end
  end

  def update
    event = Event.find(params[:event_id])
    event.messages.each do |message|
      message.update(read: true) if message.user != current_user
    end
  end

  def index
    @event = Event.find(params[:event_id])
    @message = Message.new(message_params)
  end

  private

  def message_params
    params.require(:message).permit(:content, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :index ]

  def home
    redirect_to events_path if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dashboards/show.html.erb
  <div class="dashboard">
    <h1>Hello <span class="username"><%= current_user.name %></span>,<br /> here's your events invitations.</h1>
    <% @invitations.each do |invitation| %>
      <% if invitation.status.nil? %>
        <div class="wrapper" data-controller="invitation">
            <div class="close-btn mt-2 hidden" data-invitation-target="close" data-action="click->invitation#close">X</div>
            <div class="rsvpLinks d-flex">
              <%= link_to "Approve", event_invitation_path(invitation.event, invitation, status: true), method: :patch %>
              <%= link_to "Decline", event_invitation_path(invitation.event, invitation, status: false), method: :patch %>
            </div>
            <div class="tab" data-invitation-target="tab" data-action="click->invitation#open">
                <h3><%= invitation.event.name %></h3>
                <p id="ddate"><%= invitation.event.date.to_formatted_s(:long_ordinal) %></p>
                <p id="invitor"><%=invitation.event.user.name %> invited you to collaborate</p>

              <div class = "content hidden" data-invitation-target="content" >
                <p><%= invitation.content %></p>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/events/edit.html.erb
<div class="wrapper">
  <%= simple_form_for @event do |f| %>
    <div class="form-inputs">
      <div class="inline-input d-flex">
        <%= f.input :name %>
        <%= f.input :date %>
      </div>
    <% if current_user.role == "Artist" %>
      <%= f.input :performers %>
      <%= f.input :guestlist %>
      <%= f.input :rider %>
    <% else %>
      <%= f.input :address %>
      <%= f.input :category %>
      <%= f.input :travel %>
      <%= f.input :accomodation %>
      <%= f.input :food %>
      <%= f.input :technician %>
      <%= f.input :driver %>
      <%= f.input :performers %>
    <% end %>
    </div>

    <div class="form-actions d-flex align-items-end">
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, 'Update your Event', class: "button" %>
    </div>
  <% end %>
</div>

<%= link_to 'back', event_path(@event) %>

app/views/events/index.html.erb
<div class="calender" data-calendar-target="calendarr">
  <% if current_user.role == "Artist" %>
    <%= render 'shared/calender-artist' %>
  <% else %>
    <%= render 'shared/calender-venue'%>
  <% end %>
</div>
<div class="list hidden" data-calendar-target="list">
  <% if current_user.role == "Artist" %>
    <%= render 'shared/list-artist'%>
  <% else %>
    <%= render 'shared/list-venue'%>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="wrapper">
  <h3>New Event</h3>
  <%= simple_form_for @event do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <div class="form-actions d-flex align-items-center">
        <%= f.input :date, html5: true %>
        <%= f.input :photo, as: :file %>
      </div>
      <%= f.input :address %>
      <% if current_user.role == "Artist" %>
        <%= f.input :performers %>
        <%= f.input :guestlist %>
        <%= f.input :rider %>
      <% else %>
        <%= f.input :category %>
        <%= f.input :travel %>
        <%= f.input :accomodation %>
        <%= f.input :food %>
        <%= f.input :technician %>
        <%= f.input :driver %>
        <%= f.input :performers %>
      <% end %>



    </div>

      <%= f.button :submit, 'Create Event', class: "button btn-primary" %>
  <% end %>
</div>

app/views/events/show.html.erb
<% if current_user.role == "Artist" %>
<div class="list-cont">
  <%= render "shared/show-artist" %>
</div>
<% else %>
<div class="list-cont">
  <%= render "shared/show-venue" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  <%= render 'shared/ios_pwa_links' %>
  <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <title>TURMA - your digital tour manager!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body data-controller="calendar" data-calendar-open-value="<%= params[:commit] == 'Search' %>">
    <%= render 'shared/navbar' if user_signed_in? %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' if user_signed_in? %>
   <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<% name = message.user.name || message.user.nickname %>
<% dir = "text-left" %>

<div class="<%= dir %>" id="message-<%= message.id %>">
  <small>
    <strong class="name"><%= name %></strong>
    <i class="time"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/messages/create.html.erb
<script>
  const form = document.getElementbyId('new_message')[0];
  console.log(form);
</script>

app/views/pages/_landing.html.erb
<p class="subheader">TURMA helps you to have all your important information in one place. Retreive, Update and Communciate. Streamline your touring experience with TURMA - your digital tour manager! </p>

<div class="buttons">
  <%= link_to "Log In", user_session_path, class: "button log-in active" %>
  <%= link_to "Sign up", new_user_registration_path, class: "button sign-up" %>
</div>

app/views/pages/home.html.erb
<div class="main-page">
  <%= render 'shared/logo' %>

  <div class="container">
    <div class="screen">
      <%= render 'landing' %>
    </div>
  </div>
</div>

app/views/shared/_calender-artist.html.erb
<%= month_calendar(events: @events, attribute: :date) do |date, events| %>
  <%= date.day %>
    <% events.each do |event| %>
      <% count = event.messages.where("read = false AND user_id != #{current_user.id}").count %>
      <% notification = count > 0 ? 'notification' : '' %>
      <%= link_to event_path(event) do %>
        <div class="event">
          <p class="<%= notification %>"><%= event.name %></p>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/shared/_calender.html.erb
<%= month_calendar(events: @events, attribute: :date) do |date, events| %>
  <%= date.day %>
    <% events.each do |event| %>
      <%= link_to event_path(event) do %>
        <div class="event">
              <p><%= event.name %></p>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/shared/_chat.html.erb
<div class="chatroom" data-controller="chatroom">
  <div class="messages"
        data-controller="event-subscription"
        data-event-subscription-event-id-value="<%= @event.id %>"
        data-chatroom-target="messages"
        data-chat-target="messages">
    <% @event.messages.each do |message| %>
      <%# viewName = message.user == current_user %>
      <%= render :partial => 'messages/message', :locals => { message: message } %>
    <% end %>

  <%# WHY CAN'T I PASS viewName as variable? %>
  </div>

  <%= simple_form_for([@event, @message], remote: true, data: { chatroom_target: 'formSubmit', chat_target: 'formUrl', action: 'submit->chatroom#submit' }) do |f| %>
    <%= f.input :content, label: false,  placeholder: "Message ##{@event.name}", autofocus: true, input_html: { data: { chatroom_target: 'input' } } %>
    <%= f.submit 'Send', class: "btn-primary form-send" %>
  <% end %>
</div>


<%# another script to listen to load? and scroll to bottom %>

app/views/shared/_driver.html.erb
<div class = "container">
  <div class = "justify-content-center">
    <h1>Your driver details:</h1>
    <div class = "d-flex"><h5>Pick up place:</h5> <h3>PALMA Airport</h3></div>
    <div class = "d-flex"><h5>Pick up time:</h5> <h3>17.00h</h3></div>
  </div>
  <div class = " d-flex justify-content-center">
    <%= image_tag "https://wp-assets.futurism.com/2021/10/uber-announces-50000-teslas.jpg",
    height: 150, width: 225, crop: :fill %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="close-timer alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="close-timer slider alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_flight.html.erb
<div class = "container">
  <div class = "d-flex justify-content-center">
  <%= @event.travel  %>
   </div>
  <div class = "flight_photo d-flex justify-content-center">
    <%= image_tag "boardingpass.png", height: 300, width: 250, crop: :fill %>
  </div>
</div>

app/views/shared/_hotel.html.erb
<div class = "container">
  <div class = "d-flex justify-content-center">
      <%= @event.accomodation %>
  </div>
  <div class = " d-flex justify-content-center">
    <%= image_tag "hotel.png", height: 300, width: 250, crop: :fill %>
  </div>
</div>

app/views/shared/_list.html.erb
<div class="slider sticky">
  <div class="calendar-heading">
    <div class="prev"><</div>
    <div class="calendar-title">November 2021</div>
    <div class="next">></div>
  </div>
</div>


<% @events_month.each do |event| %>
    <div class="tab">
    <%= link_to event_path(event) do %>
        <h3><%= event.name %></h3>
        <span><%= event.date.to_formatted_s(:long_ordinal) %></span>
    <%end%>
      </div>
<% end %>

app/views/shared/_navbar.html.erb
<% pen_invitations = current_user.invitations.where(status: nil).count %>
<div class="navbar-container sticky">
  <% if user_signed_in? %>
  <% invitations = pen_invitations > 0 ? 'new-invitations' : '' %>
    <div class = "avatar">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40, width: 40, crop: :fill, class: invitations %>
      <% else %>
        <%= image_tag "https://thumbs.dreamstime.com/b/icono-de-avatar-dj-estilo-simple-vectorial-para-dise%C3%B1o-web-aislado-en-fondo-blanco-164370922.jpg", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40, width: 40, crop: :fill, class: invitations %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
        <%= link_to dashboards_path, class: "dropdown-item" do %>
          invitations <span class="notification"><%= pen_invitations > 0 ? "(#{pen_invitations})" : "" %></span>
        <% end %>
        <%= link_to "edit profile", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% end %>

  <div class="wrapper search_items" data-controller="search">
    <div class="search_bar" data-search-target="search">
      <%= form_tag events_path, method: :get, data: { search_target: 'searchForm' } do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search an event",
          data: { search_target: 'input' } %>
        <%= submit_tag "Search",data: { search_target: 'submit' }, class: "search_btn btn-primary" %>
      <% end %>
    </div>
    <i class="fas fa-search search-icon" data-search-target="open"  data-action="click->search#openSearch"></i>

  </div>
</div>

app/views/shared/_overview-artist.html.erb
<div class = "event_pic justify-content-center">
  <% if @event.photo.attached? %>
    <%= cl_image_tag @event.photo.key, height: 200, width: 150, crop: :fill %>
  <% else %>
    <%= image_tag "https://www.squeaker.net/image/event/event-placeholder-list.png", height: 150, width: 250, crop: :fill %>
  <% end %>
</div>

<div class="details">
  <h6><%= @event.date %></h6>
  <h6><%= @event.address %></h6>
</div>

<div class="map" style="width: 100%; height: 150px;"
data-controller="mapbox"
data-mapbox-markers-value="<%= @markers.to_json %>"
data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div id="accordion">
  <div class="invitation">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          INVITATION
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <%= simple_form_for [@event, @invitation] do |f| %>
          <div class = "user_text" ><%= f.text_field :user_id, placeholder: 'Who are you looking for?' %></div>
          <%= f.input :content, placeholder: 'text' %>
          <div class = "btn"><%= f.submit "submit" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class ="options">
  <h5><%= link_to 'edit', edit_event_path %></h5>
  <h5><%= link_to "delete", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %></h5>
</div>

app/views/shared/_overview-venue.html.erb
<div class = "event_pic justify-content-center">
  <% if @event.photo.attached? %>
    <%= cl_image_tag @event.photo.key, height: 200, width: 150, crop: :fill %>
  <% else %>
    <%= image_tag "https://www.squeaker.net/image/event/event-placeholder-list.png", height: 150, width: 250, crop: :fill %>
  <% end %>
</div>

<div class="details">
  <h6><%= @event.date %></h6>
  <h2><%= @event.performers %></h2>
</div>

<div class="map" style="width: 100%; height: 150px;"
data-controller="mapbox"
data-mapbox-markers-value="<%= @markers.to_json %>"
data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div id="accordion">
  <div class="invitation">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          INVITATION
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <%= simple_form_for [@event, @invitation] do |f| %>
          <div class = "user_text" ><%= f.text_field :user_id, placeholder: 'Who are you looking for?' %></div>
          <%= f.input :content, placeholder: 'text' %>
          <div class = "btn"><%= f.submit "submit" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class ="options">
<%= link_to 'edit', edit_event_path %>
<%= link_to "delete", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %>
</div>

app/views/shared/_performers.html.erb
<div class = "container">
  <div class = "d-flex justify-content-center">
    <%= @event.performers %>
  </div>
</div>

app/views/shared/_rider.html.erb
<div class = "container">
  <div class = "d-flex justify-content-center">
    <%= @event.rider %>
  </div>
</div>

app/views/shared/_show-venue.html.erb
<div class= "event-show" >
  <div class="head-calendar">
    <div class= "slider mb-4">
      <div data-controller="overview">
        <div class= "hidden" data-overview-target="close" data-action="click->overview#close">X</div>
        <div data-overview-target="tab" data-action="click->overview#open">
          <h1><%= @event.name %></h1>
          <div class = "overview hidden" data-overview-target="content" >
            <%= render 'shared/overview-artist', :locals => { :event => @event } %>
        </div>
      </div>
    </div>
  </div>
</div>

    <% count = @event.messages.where("read = false AND user_id != #{current_user.id}").count %>
    <% notification = count > 0 ? 'notification' : '' %>

    <div class="wrapper" data-controller="chat">
      <div class="close-btn mt-2 hidden" data-chat-target="close" data-action="click->chat#close">X</div>
      <div class="tab <%= notification %>" data-chat-target="tab" data-action="click->chat#open">
        <h3>Chat</h3>
        <span><%= @event.user.name %><%= @event.invitations.count > 0 ? " & #{@event.invitations[0].user.name}" : '' %> </span>
        <div class = "chat hidden" data-chat-target="content" >
          <%= render 'shared/chat', :locals => { :event => @event, :invitation => @invitation, :message => @message } %>
        </div>
      </div>
    </div>

  <% unless @event.performers.nil? ||  @event.performers.empty?  %>
    <div class="wrapper" data-controller="performers">
      <div class="close-btn mt-2 hidden" data-performers-target="close" data-action="click->performers#close">X</div>
      <div class="tab" data-performers-target="tab" data-action="click->performers#open">
        <div class="d-flex justify-content-between">
          <h3>Performers</h3>
        </div>
        <div class = "performers hidden" data-performers-target="content" >
          <%= render 'shared/performers', :locals => { :event => @event } %>
        </div>
      </div>
    </div>
  <% end %>

  <% unless @event.rider.nil? ||  @event.rider.empty?  %>
    <div class="wrapper" data-controller="rider">
      <div class="close-btn mt-2 hidden" data-rider-target="close" data-action="click->rider#close">X</div>
      <div class="tab" data-rider-target="tab" data-action="click->rider#open">
        <div class="d-flex justify-content-between">
          <h3>Rider</h3>
        </div>
        <div class = "rider hidden" data-rider-target="content" >
          <%= render 'shared/rider', :locals => { :event => @event } %>
        </div>
      </div>
    </div>
  <% end %>


  <% unless @event.guestlist.nil? ||  @event.guestlist.empty?  %>
    <div class="wrapper" data-controller="guestlist">
      <div class="close-btn mt-2 hidden" data-guestlist-target="close" data-action="click->guestlist#close">X</div>
      <div class="tab" data-guestlist-target="tab" data-action="click->guestlist#open">
        <div class="d-flex justify-content-between">
          <h3>Guestlist</h3>
        </div>
        <div class = "guestlist hidden" data-guestlist-target="content" >
          <%= render 'shared/guestlist', :locals => { :event => @event } %>
        </div>
      </div>
    </div>
  <% end %>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">

  <div class="head-calendar">
    <div class="slider">
      <div class="calendar-heading">
          <div class="prev"><%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view %></div>
          <div class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></div>
          <div class="next"><%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view %></div>
      </div>
    </div>
  </div>

   <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<div class="container">
  <div id="users">
    <% @users.each do |user|%>
      <h1><%= user.name%></h1>
      <h1><%= user.email%></h1>
      <h1><%= user.nickname%></h1>
    <% end %>
  </div>
</div>